/**
 * Weekly report generator.
 * Runs a structured Huginn query to produce a 4-section weekly report
 * covering top signals, entity movements, substrate trends, and narrative gaps.
 */

export type WeeklyReportSection = {
  title: string;
  content: string;
  confidence: number;
};

export type WeeklyReport = {
  generatedAt: string;
  windowDays: number;
  sections: WeeklyReportSection[];
  overallConfidence: number;
};

const REPORT_PROMPTS: Record<string, string> = {
  topSignals:
    "Summarize the top Capital Fixation signals from the past 7 days, ordered by priority. Include confidence levels and source references.",
  entityMovements:
    "Which entities showed the largest Capital Fixation score changes in the past 7 days? For each, note whether the change is positive or negative and the primary substrate driver.",
  substrateTrends:
    "Give a sector-by-sector overview of Capital Fixation activity this week. Which substrates are showing the most movement or unusual patterns?",
  narrativeGaps:
    "Which entities currently have the largest Narrative-Reality Gap? What reality signals contradict the prevailing narrative for each?"
};

const SECTION_TITLES: Record<string, { en: string; ja: string }> = {
  topSignals:       { en: "Top Signals",          ja: "トップシグナル" },
  entityMovements:  { en: "Entity Movements",     ja: "エンティティ動向" },
  substrateTrends:  { en: "Substrate Trends",     ja: "サブストレートトレンド" },
  narrativeGaps:    { en: "Narrative-Reality Gaps", ja: "ナラティブ乖離" }
};

export type HuginnCallFn = (
  question: string,
  orgId: string
) => Promise<{ answer: string; confidence: number }>;

export async function generateWeeklyReport(
  callHuginn: HuginnCallFn,
  orgId: string,
  locale: "en" | "ja" = "en"
): Promise<WeeklyReport> {
  const sections: WeeklyReportSection[] = [];
  const keys = Object.keys(REPORT_PROMPTS) as Array<keyof typeof REPORT_PROMPTS>;

  for (const key of keys) {
    const prompt = REPORT_PROMPTS[key];
    try {
      const result = await callHuginn(prompt, orgId);
      sections.push({
        title: SECTION_TITLES[key]?.[locale] ?? key,
        content: result.answer,
        confidence: result.confidence
      });
    } catch (err) {
      sections.push({
        title: SECTION_TITLES[key]?.[locale] ?? key,
        content: `Report section unavailable: ${err instanceof Error ? err.message : String(err)}`,
        confidence: 0
      });
    }
  }

  const overallConfidence =
    sections.reduce((sum, s) => sum + s.confidence, 0) / Math.max(sections.length, 1);

  return {
    generatedAt: new Date().toISOString(),
    windowDays: 7,
    sections,
    overallConfidence
  };
}

export function formatReportAsSlackBlocks(report: WeeklyReport): unknown[] {
  const blocks: unknown[] = [
    {
      type: "header",
      text: {
        type: "plain_text",
        text: `Odim Weekly Report — ${report.generatedAt.slice(0, 10)}`
      }
    },
    {
      type: "context",
      elements: [
        {
          type: "mrkdwn",
          text: `Overall confidence: *${Math.round(report.overallConfidence * 100)}%* · Generated by Huginn Reality Intelligence`
        }
      ]
    },
    { type: "divider" }
  ];

  for (const section of report.sections) {
    blocks.push(
      {
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*${section.title}* _(${Math.round(section.confidence * 100)}% conf.)_\n${section.content.slice(0, 2800)}`
        }
      },
      { type: "divider" }
    );
  }

  return blocks;
}
